# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5061781aa5053d63f1fb57fd1672f9c1fc422ac412aa92179abf7bbe7f2ecb57e42fdcbd67f08bb7f2e68997018fc68c7682440235b5d6a5e7b721baa69e160

test:
  secret_key_base: 8277dacddb7e833c6d365b42c7acdab752a1aa9bc8efe7d010f1a79e6114b06fb66be04a2371c28e5d0b277f87dca9bd377b8cefd4f5f3d620afef0630e75082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
